# Generated by Django 4.2 on 2025-06-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('sport', 'sport'), ('musique', 'musique'), ('Cinema', 'Cinema')], max_length=20)),
                ('state', models.BooleanField(default=True)),
                ('nbr_participants', models.IntegerField()),
                ('evt_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
