# Generated by Django 4.2 on 2025-07-09 18:33

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event', '0004_participants_event_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name': 'Participant'},
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='nbr_participants',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='participants',
            unique_together={('event', 'person')},
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gt', datetime.datetime(2025, 7, 9, 19, 33, 36, 661935))), name='Please check the event date'),
        ),
    ]
